### ISSUE TITLE
Cant install/ invalid signature

### ISSUE THREAD

**Issue by ghost** [lopez05656/LineageOS-Eleven-Material-Theme#1]
Hi, when I try to install the app with my phone I get an installastion error , when I try with adb it gave me:" Failure [INSTALL_FAILED_UPDATE_INCOMPATIBLE: Package org.lineageos.eleven signatures do not match previously installed version; ignoring!]" .
I'm using a pixel 3 with lineageos 17.1.
I managed to install the app with an other distribution without eleven installed by default and it worked well.

**Comment by ghost** [comment]
Ok, I managed to get it install here what I did :
adb root
adb disable-verity
adb reboot
adb root
adb remount
adb shell
cd /product/priv-app/Eleven/
rm -r *
exit 
adb push ./Eleven.apk /product/priv-app/Eleven  (where Eleven.apk is file release renamed)
adb reboot (not sure it's usefull)
adb root
adb enable-verity
adb reboot

Now it's working but it will probably reinstall to original app in the next Lineage update, I hope it wont

Edit: you can use debloat script on magisk to uninstall original app, it's much easier
If someone needs help you can get more information here: 
https://www.droidviews.com/debloater-magisk-module-uninstall-system-apps-android/

**Comment by BlueN1nja1** [comment]
Alright. I'm trying to make it official in LineageOS 18.1, so hang tight!

**Comment by BlueN1nja1** [comment]
As of today, it's official in LineageOS 18.1! This issue has been closed.
