### ISSUE TITLE
Beta crashing on OneUI 1.1 (Android 9 Pie)

### ISSUE THREAD

**Issue by lucmsilva651** [lopez05656/LineageOS-Eleven-Material-Theme#10]
Hey! Are you okay? I am here to report a bug from the app, since the ver 5.6.0.1_9 the app no longer opens. I click to open and an stop message appears. Can you fix this?

~~~~
oh yeah, this is not desciclopedia

**Comment by BlueN1nja1** [comment]
Sure, can you send me a log from when the crash happened?

**Comment by lucmsilva651** [comment]
sorry for not responding the message, its dont making a log, its just crashing

**Comment by BlueN1nja1** [comment]
Ah. I see the problem. I'll have a release out soon. Apologies on the late response.
