### ISSUE TITLE
Corrupt album art image when run under Android 11

### ISSUE THREAD

**Issue by fungko** [lopez05656/LineageOS-Eleven-Material-Theme#14]
The album art images are corrupted or not loaded correctly under Android 11. Android 10 or below does not have such problem. May be some breaking changes after Android 11. Is it related to the following description?

https://developer.android.com/reference/android/provider/MediaStore.Audio.AlbumColumns

**Comment by fungko** [comment]
After further debugging, this bug is cause by the getArtWorkFromFile funtion inside ImageCache.java.

    public final Bitmap getArtworkFromFile(final Context context, final long albumId) {
        if (albumId < 0) {
            return null;
        }
        Bitmap artwork = null;
        waitUntilUnpaused();

        ParcelFileDescriptor parcelFileDescriptor = null;
        try {
            final Uri uri = ContentUris.withAppendedId(mArtworkUri, albumId);
            parcelFileDescriptor = context.getContentResolver().openFileDescriptor(uri, "r");
            if (parcelFileDescriptor != null) {
                final FileDescriptor fileDescriptor = parcelFileDescriptor.getFileDescriptor();
                artwork = BitmapFactory.decodeFileDescriptor(fileDescriptor);
            }
        } catch (final IllegalStateException e) {
            // Log.e(TAG, "IllegalStateExcetpion - getArtworkFromFile - ", e);
        } catch (final FileNotFoundException e) {
            // Log.e(TAG, "FileNotFoundException - getArtworkFromFile - ", e);
        } catch (final OutOfMemoryError evict) {
            // Log.e(TAG, "OutOfMemoryError - getArtworkFromFile - ", evict);
            evictAll();
        } finally {
            IoUtils.closeQuietly(parcelFileDescriptor);
        }
        return artwork;
    }

File not found exception thrown on the line:
**parcelFileDescriptor = context.getContentResolver().openFileDescriptor(uri, "r");**
when the app is run under Android 11. Not all music have the exception, but the artwork bitmap get from these items are corrupted bitmap.

**Comment by lopez05656** [comment]
Thanks for the logs. I'll look into this.

**Comment by BlueN1nja1** [comment]
Closed in favor of Twelve

**Comment by BlueN1nja1** [comment]
Closed in favor of Twelve
