### ISSUE TITLE
feature request: search function

### ISSUE THREAD

**Issue by ilf** [lopez05656/LineageOS-Eleven-Material-Theme#17]
app: org.lineageos.eleven
name: Eleven
version: 4.2.0

With lots of audio files, Eleven gets really hard to navigate and find things.
A search function would be awesome. Lots of people [have requested this](https://www.reddit.com/r/LineageOS/comments/i1s0fp/eleven_music_player_does_not_have_a_search/).
This existed previously, was [removed in 2020](https://github.com/LineageOS/android_packages_apps_Eleven/commit/145c292a363318f0eadd8b1333472821459bd026), and [said to be planned again in 2022](https://github.com/lopez05656/Eleven/issues/8#issuecomment-1229243300).

Would be great to have this back. Thanks.

(Moving this out of #8, because that's a mix of multiple issues.)

**Comment by BlueN1nja1** [comment]
Closed in favor of Twelve
