### ISSUE TITLE
feature request: fast scroll

### ISSUE THREAD

**Issue by ilf** [lopez05656/LineageOS-Eleven-Material-Theme#18]
app: org.lineageos.eleven
name: Eleven
version: 4.2.0

With lots of audio files, Eleven gets really hard to navigate and find things.
In addition to search (#17), **fast scroll** would be awesome.

https://developer.android.com/reference/android/widget/AbsListView.html#attr_android:fastScrollEnabled
https://developer.android.com/reference/android/widget/AbsListView.html#setFastScrollEnabled(boolean)

[com.android.contacts](https://android.googlesource.com/platform/packages/apps/Contacts/) uses this, apparently like this:

```
$ grep -Ri fastscroll
src/com/android/contacts/list/ContactEntryListFragment.java:            mListView.setFastScrollEnabled(hasScrollbar);
src/com/android/contacts/list/ContactEntryListFragment.java:                mListView.setFastScrollEnabled(!flag);
src/com/android/contacts/list/ContactEntryListFragment.java:        mListView.setFastScrollEnabled(!isSearchMode());
res/layout/contact_list_content.xml:                android:fastScrollEnabled="true"
res/layout/join_contact_picker_list_content.xml:            android:fastScrollEnabled="true"
res/layout/contact_picker_content.xml:        android:fastScrollEnabled="true"/>
```

**Comment by BlueN1nja1** [comment]
Closed in favor of Twelve
