### ISSUE TITLE
Hi, this message show when i try to make a playlist. 

### ISSUE THREAD

**Issue by lpred** [lopez05656/LineageOS-Eleven-Material-Theme#4]
This is the log erro URL.

https://bin.kv2.dev/~620ee645410e7c32e6699648

**Comment by lpred** [comment]
Sou brasileiro (brazilian). O APP fecha quando vou fazer uma playlist. Estou no Android 11, mas no Android 10 tambem dava esse erro.

**Comment by lopez05656** [comment]
Thanks for the log, I'll try to fix this as soon as I can.

**Comment by BlueN1nja1** [comment]
Closed in favor of Twelve
