### ISSUE TITLE
Please scroll title of track

### ISSUE THREAD

**Issue by realmebrand** [lopez05656/LineageOS-Eleven-Material-Theme#5]
As an oldtimer, I still prefer smaller mobile phones instead of 6 inches or larger!
Jokes apart, it would be nice long titles can scroll.
Thanks for your work

**Comment by BlueN1nja1** [comment]
No Problem, I'll see if I can add it in the next beta.

**Comment by BlueN1nja1** [comment]
Keep an eye out for 6.0.0 Beta 2.1, that beta release will add title scrolling.

**Comment by BlueN1nja1** [comment]
6.0.0 Beta 2.1 has been released with Title Scrolling! This issue has been closed.
