### ISSUE TITLE
Add the current track to a playlist button 

### ISSUE THREAD

**Issue by JoPatate** [lopez05656/LineageOS-Eleven-Material-Theme#7]
Since the update to LineageOS 19.1, the "add to playlist" button of the current track on the play screen has disappeared.
Is it a choice or a bug ?
**A great thanks for your work!**

**Comment by BlueN1nja1** [comment]
No Problem! As for the missing Playlist button, it's a bug. It'll be fixed in the next beta. Keep an eye out for 6.0.0 Beta 2.1, it'll add back the playlist button.

**Comment by BlueN1nja1** [comment]
As of now, this bug is fixed as of 6.0.0 Beta 2.1! This issue is now closed.

**Comment by JoPatate** [comment]
Thanks a lot for your work!

**Comment by BlueN1nja1** [comment]
You're welcome.
