### ISSUE TITLE
Old features

### ISSUE THREAD

**Issue by alvrmiguel** [lopez05656/LineageOS-Eleven-Material-Theme#8]
I was trying the lastest beta 6.0.0 beta 2, can you put search in the app? To search for the songs pls. And in the 6.0.0 beta 2 there is no option to repeat tracks and option to shuffle like 5.6.0.1. thanks

**Comment by BlueN1nja1** [comment]
No Problem! Search is a planned feature. But it'll take a while to implement it as it requires a full rewrite because of Scoped Storage. But I'm pretty sure that there is an option to repeat tracks and shuffle them. To find those options, you have to swipe up on the player ui and then you'll find the shuffle and repeat buttons next to the skip buttons.

**Comment by sesselastronaut** [comment]
One up for the search function!

**Comment by MeTalOneOEight** [comment]
> But I'm pretty sure that there is an option to repeat tracks and shuffle them. To find those options, you have to swipe up on the player ui and then you'll find the shuffle and repeat buttons next to the skip buttons.

There's shuffle in the menu somewhere, but no repeat or shuffle button in the UI if you swipe up.
Maybe you didn't pack the assets?

**Comment by BlueN1nja1** [comment]
Can you send me a screenshot just to verify? Thanks.

**Comment by MeTalOneOEight** [comment]
Here is the screenshot, as you see no shuffle or repeat next to the skip
buttons.

![Screenshot_2023-02-24-07-36-07-686_org lineageos eleven](https://user-images.githubusercontent.com/124566425/221144102-ac4db4b4-10ae-4dc0-a952-b27868d912dc.jpg)

**Comment by BlueN1nja1** [comment]
What is your Android Version and what version of Eleven are you using?

**Comment by MeTalOneOEight** [comment]
Android 12 in the MIUI 13 variant.
Eleven 6.0.0 beta 2.1

**Comment by alvrmiguel** [comment]
On my phone I can't see the shuffle and the repeat buttons too.
A13 Poco F1 AOSP
6.0.0 Beta 2.2

![Screenshot_20230318-223742](https://user-images.githubusercontent.com/110349958/226149029-3a2656a4-4cdd-43e4-89a6-460d9b8af0d3.png)

**Comment by BlueN1nja1** [comment]
Hmm... I'll look into this.

**Comment by alpenamilch** [comment]
Could you tell the version when the search was removed? It is really uncomfortable (especially when wife complains!)

**Comment by BlueN1nja1** [comment]
I believe this version still has search, but search may crash because of scoped storage: https://github.com/lopez05656/Eleven/releases/tag/5.4.0-Pre4

**Comment by BlueN1nja1** [comment]
Also, I'll push out a build with a fix for the Missing Shuffle and Repeat buttons shortly.

**Comment by BlueN1nja1** [comment]
6.0.0 Beta 3 is out. The Shuffle and Repeat buttons should be visible now.

**Comment by MeTalOneOEight** [comment]
Shuffle and Repeat are there now with beta 3.
Checked on Poco F2 Pro with Android 12/MIUI 14

**Comment by BlueN1nja1** [comment]
Closed in favor of Twelve
