### ISSUE TITLE
Beta is crashing on OxygenOS 11.3

### ISSUE THREAD

**Issue by calexil** [lopez05656/LineageOS-Eleven-Material-Theme#9]
[logcat.txt](https://github.com/lopez05656/Eleven/files/9805093/logcat.txt)

not sure what you can make of it

**Comment by BlueN1nja1** [comment]
This bug should be fixed as of 6.0.0 beta 2.2. Let me know if you need anything else.

**Comment by calexil** [comment]
@lopez05656 working perfect! tysm, eleven is SOOOOO much cleaner than other music players

**Comment by calexil** [comment]
@lopez05656 not sure if this is even possible, but is there any way to add back in 'start playback on bluetooth connect' for some reason that setting has dissappeared from android, but I know it can still be done at the app level(pearl music player for example).
